import turtle
obj=turtle.Turtle()

obj.begin_fill()
obj.fillcolor("purple")
obj.forward(150)
obj.left(90)
obj.forward(70)
obj.left(90)
obj.forward(150)
obj.left(90)
obj.forward(70)
obj.end_fill()

obj.left(90)
obj.begin_fill()
obj.fillcolor("white")
obj.forward(70)
obj.left(90)
obj.forward(30)
obj.right(90)
obj.forward(15)
obj.right(90)
obj.forward(30)
obj.right(90)
obj.forward(15)
obj.end_fill()
obj.forward(70)
obj.right(90)
obj.begin_fill()
obj.fillcolor("yellow")
obj.forward(70)

obj.right(40)
obj.forward(100)
obj.right(92)
obj.forward(113)
obj.right(138)
obj.forward(150)
obj.end_fill() 

obj.right(180)
obj.pencolor("white")
obj.forward(250)
obj.left(90)
obj.begin_fill()
obj.fillcolor("brown")
obj.forward(15)
obj.right(90)
obj.forward(30)
obj.right(90)
obj.forward(15)
obj.right(90)
obj.forward(30)
obj.end_fill()
obj.right(180)
obj.forward(30)
obj.right(90)
obj.forward(100)
obj.right(180)
obj.pencolor("black")
obj.forward(150)
obj.begin_fill()
obj.fillcolor("yellow")
obj.circle(16)
obj.end_fill()

turtle.done()
        